# https://fastapi.tiangolo.com/advanced/behind-a-proxy/#testing-locally-with-traefik

[entryPoints]
  [entryPoints.http]
    address = ":6701"

[providers]
  [providers.file]
    filename = "routes.toml"

[api]
  insecure = true

[log]
  level = "DEBUG"
