# https://fastapi.tiangolo.com/advanced/behind-a-proxy/#testing-locally-with-traefik

[entryPoints]
  [entryPoints.http]
    address = ":6701"

[providers]
  [providers.file]
    directory = "./traefik-config/"
    watch = true

[api]
  insecure = true
