name: fyp23-container
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=1.13.1
  - pytorch-cuda=11.6
  - torchvision=0.14.1
  - torchaudio=0.13.1
  # Font-diff
  - tqdm
  - opencv
  - scikit-learn
  - pillow
  - tensorboardX
  - blobfile>=1.0.5
  - mpi4py
  - openmpi # for Linux
  # - msmpi # for Windows
  - attrdict
  - PyYAML
  - numpy<2.0.0
  # New Font Generation from Classic Calligraphy
  - fonttools
  - matplotlib
  # Generative Calligraphy Website
  - fastapi[standard]>=0.115.8,<0.116.0
  - pytest>=8.4.1,<9.0
  - pytest-asyncio
  - pytest-timeout
