dropout: 0.1
chara_nums: 3000
diffusion_steps: 1000
noise_schedule: 'linear'
image_size: 80
num_channels: 128
num_res_blocks: 3
batch_size: 1 #5 do not change
num_samples: 3000 #210 # number of characters to be generated
attention_resolutions: '40, 20, 10'
use_ddim: True
timestep_respacing: ddim25
